Repository snapshot-labs/snapshot, pull requests merged in 2022-05, with the labels that each got.

#2446 Fix profile vote icon color and delegation
  src/components/ProfileAboutDelegate.vue
  src/components/ProfileActivityListItem.vue
  src/locales/default.json
Labels: bug

#2461 Fix playground address checksum issue
  src/helpers/interfaces.ts
  src/plugins/quorum/index.ts
  src/plugins/safeSnap/components/Config.vue
  src/views/Explore.vue
  src/views/Playground.vue
Labels: bug

#2464 Fix controller setup form
  src/components/SetupController.vue
Labels: bug

#2448 Use Stamp for space avatars
  src/components/AvatarSpace.vue
  src/components/NavbarNotifications.vue
  src/components/ProfileActivityListItem.vue
  src/components/TheNavbar.vue
  src/views/ProfileActivity.vue
Labels: enhancement

#2466 Fix bugs, start refactor settings and add typescript
  src/components/ModalControllerEdit.vue
  src/composables/useExtendedSpaces.ts
  src/composables/useSpaceController.ts
  src/helpers/interfaces.ts
  src/views/Space.vue
  src/views/SpaceSettings.vue
Labels: bug

#2469 Rinkeby ENS space
  src/components/Modal/UnsupportedNetwork.vue
  src/components/SetupController.vue
  src/composables/useSpaceController.ts
  src/locales/default.json
  src/style.scss
  src/views/SpaceSettings.vue
Labels: enhancement

#2470 Fix bugs, refactor and add typescript (proposal creation)
  src/components/Block/Results.vue
  src/components/ModalSpacesListItem.vue
  src/components/ResultsItem.vue
  src/components/SpaceCreateContent.vue
  src/components/SpaceCreateVoting.vue
  src/components/SpaceCreateWarnings.vue
  src/components/TheSidebar.vue
  src/composables/useExtendedSpaces.ts
  src/composables/useSpaceCreateForm.ts
  src/helpers/interfaces.ts
  src/router.ts
  src/views/SpaceCreate.vue
  src/views/SpaceSettings.vue
Labels: bug, refactor
