Repository snapshot-labs/snapshot, pull requests merged in 2022-06, with the labels that each got.

#2567 Refactor and network combobox
  src/components/AutocompleteNetwork.vue
  src/components/BaseAutocomplete.vue
  src/components/BaseCombobox.vue
  src/components/BaseListboxMultiple.vue
  src/components/BasePill.vue
  src/components/ComboboxNetwork.vue
  src/components/ModalStrategy.vue
  src/components/SetupProfile.vue
  src/components/StrategiesBlock.vue
  src/components/StrategiesBlockItem.vue
  src/views/SpaceSettings.vue
Labels: refactor

#2634 Link to playground in strategy settings
  src/components/ModalStrategies.vue
  src/components/ModalStrategy.vue
  src/helpers/b64.ts
  src/locales/default.json
  src/views/PlaygroundView.vue
Labels: enhancement

#2329 feat: Treasury space page
  package.json
  src/components/BaseBlock.vue
  src/components/BaseButton.test.js
  src/components/ButtonBack.vue
  src/components/ComboboxNetwork.vue
  src/components/IndicatorAssetsChange.spec.js
  src/components/IndicatorAssetsChange.vue
  src/components/ModalTreasury.vue
  src/components/SettingsStrategiesBlock.vue
  src/components/SettingsTreasuriesBlock.vue
  src/components/SettingsTreasuriesBlockItem.vue
  src/components/SpaceSidebarNavigation.vue
  src/components/TreasuryAssetsList.vue
  src/components/TreasuryAssetsListItem.spec.js
  src/components/TreasuryAssetsListItem.vue
  src/components/TreasuryWalletsList.spec.js
  src/components/TreasuryWalletsList.vue
  src/components/TreasuryWalletsListItem.spec.js
  src/components/TreasuryWalletsListItem.vue
  src/composables/useIntl.ts
  src/composables/useSpaceSettingsForm.ts
  src/composables/useTreasury.ts
  src/helpers/covalent.ts
  src/helpers/interfaces.ts
  src/helpers/profile.ts
  src/helpers/queries.ts
  src/helpers/utils.test.js
  src/locales/default.json
  src/router.ts
  src/views/DelegateView.vue
  src/views/PlaygroundView.vue
  src/views/SpaceCreate.vue
  src/views/SpaceProposal.vue
  src/views/SpaceSettings.vue
  src/views/SpaceTreasury.vue
  src/views/SpaceView.vue
  vite.config.ts
  vitest.ts
  yarn.lock
Labels: enhancement

#2664 Rename voting class methods
  package.json
  src/components/ProposalResultsList.vue
  src/components/ProposalResultsListItem.vue
  src/helpers/interfaces.ts
  src/helpers/snapshot.ts
  src/plugins/quorum/components/CustomBlock.vue
  src/views/SpaceProposal.vue
  yarn.lock
Labels: dependencies, refactor
